name: Push-triggered Job

on:
  push:
    branches:
      - main  # Adjust to your branch name

jobs:
  run-push-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.9'

    - name: Install dependencies
      run: |
        pip install -r backend/requirements.txt

    - name: Print environment variables
      run: |
        echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}"
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}"
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}"
        echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}"
        echo "POSTGRES_URL=${{ secrets.POSTGRES_URL }}"
      env:
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        POSTGRES_URL: ${{ secrets.POSTGRESS_URL }}
      
    - name: Run Python script
      env:
        POSTGRES_URL: ${{ secrets.POSTGRES_URL }}  # Correct the secret name
      run: |
        cd backend
        python main.py --job
