name: Run Scheduled Job

on:
  schedule:
    - cron: "0 9 * * *"  # This runs every day at 9:00 AM UTC
  workflow_dispatch:  # Allows you to trigger the workflow manually

jobs:
  run-job:
    runs-on: ubuntu-latest

    env:  # Define environment variables from secrets
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the job script
        run: |
          source venv/bin/activate
          python backend/job.py
